"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
import dj_database_url

# Строим пути внутри проекта вот так: BASE_DIR / 'subdir'
BASE_DIR = Path(__file__).resolve().parent.parent

# Секретный ключ берется из файла .env
SECRET_KEY = config('SECRET_KEY')

# Режим отладки: если в .env написано DEBUG=True — будет True, если ничего нет — по умолчанию False
DEBUG = config('DEBUG', default=False, cast=bool)

# Разрешенные хосты (для разработки разрешены все)
ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = ['https://academy-1c.onrender.com']
# ==============================================================================
# ПРИЛОЖЕНИЯ СИСТЕМЫ
# ==============================================================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Твои крутые приложения для 1С Академии
    'references',
    'documents',
    'warehouse',
    'accounting',
    'reports',
    'users',
]

# ==============================================================================
# ПРОМЕЖУТОЧНОЕ ПО (MIDDLEWARE)
# ==============================================================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

# ==============================================================================
# ШАБЛОНЫ (HTML)
# ==============================================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Главная папка шаблонов в корне проекта
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# ==============================================================================
# БАЗА ДАННЫХ
# ==============================================================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ==============================================================================
# ВАЛИДАЦИЯ ПАРОЛЕЙ
# ==============================================================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ==============================================================================
# ЛОКАЛИЗАЦИЯ И ВРЕМЯ (Кыргызстан, Бишкек)
# ==============================================================================
LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = 'Asia/Bishkek'
USE_I18N = True
USE_TZ = True

# ==============================================================================
# СТАТИКА И МЕДИА (Картинки, Стили, Скрипты)
# ==============================================================================
# Префикс в URL-адресе для статических файлов
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Настройки для загружаемых файлов (аватарки, документы и т.д.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Хранилище для WhiteNoise (сжимает файлы и кэширует их, чтобы сайт летал)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
# АВТОРИЗАЦИЯ И ПОЛЬЗОВАТЕЛИ
# ==============================================================================
AUTH_USER_MODEL = 'auth.User'

LOGIN_URL = '/users/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/users/login/'

# Кастомизация встроенной админки Django под твой стиль
ADMIN_SITE_HEADER = '1С Академия'
ADMIN_SITE_TITLE = '1С Академия'
ADMIN_INDEX_TITLE = 'Управление системой'

import os
import dj_database_url

# Для Render — PostgreSQL

# if os.environ.get('DATABASE_URL'):
#     DATABASES = {
#         'default': dj_database_url.parse(os.environ.get('DATABASE_URL'))
#     }